### PR TITLE
add version 5.1.16

### PR DESCRIPTION
**Pull request by matthiasdiener**
cc #9

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
This is ready for review @conda-forge/bash

**Comment by matthiasdiener** [comment]
A gentle ping for a review @conda-forge/bash @conda-forge/core

**Comment by hmaarrfk** [comment]
Remind me again why we have so many patches that aren't accepted upstream? It seems a little strange. Some seem to change behavior.

**Comment by beckermr** [comment]
I wouldn't be so cavalier about removing patches. Those appear to be from upstream and someone took the time to add them for a reason. It should be better documented maybe but we should know what we are or are not doing.

**Comment by matthiasdiener** [comment]
> Remind me again why we have so many patches that aren't accepted upstream? It seems a little strange. Some seem to change behavior.

I just noticed that bash does publish patched tarballs, which makes the build much simpler imho.

**Comment by matthiasdiener** [comment]
> I wouldn't be so cavalier about removing patches. Those appear to be from upstream and someone took the time to add them for a reason. It should be better documented maybe but we should know what we are or are not doing.

The patches were just to update a minor version of bash (5.0) to the patched release (5.0.18), they shouldn't be necessary anymore. I'll use the tarball for 5.1(.16), without needing separate patches.

**Comment by hmaarrfk** [comment]
Understood. This makes alot of sense.

**Review by hmaarrfk — APPROVED** [review]

**Comment by matthiasdiener** [comment]
Could you please merge this @hmaarrfk ?

**Pull request merged**
